import type { College, Exam, Review } from '@/types'

export const colleges: College[] = [
  {
    id: '1',
    name: 'IIT Bombay',
    location: 'Mumbai',
    state: 'Maharashtra',
    rank: 1,
    rankingBody: 'NIRF',
    stream: 'Engineering',
    type: 'government',
    avgCTC: 18.5,
    highestCTC: 2.4,
    cutoff: '98.5+',
    cutoffExam: 'JEE Advanced',
    tags: ['Govt. funded', 'NAAC A++', 'NBA', 'ABET'],
    accreditation: ['NAAC A++', 'NBA'],
    established: 1958,
    totalFee: 2.2,
    matchScore: 92,
    admissionChance: 68,
    verified: true,
  },
  {
    id: '2',
    name: 'AIIMS Delhi',
    location: 'New Delhi',
    state: 'Delhi',
    rank: 1,
    rankingBody: 'NIRF Medical',
    stream: 'Medical',
    type: 'government',
    avgCTC: 14.0,
    highestCTC: 38,
    cutoff: '715+',
    cutoffExam: 'NEET',
    tags: ['Govt. funded', 'NAAC A+', 'Premier Institute'],
    accreditation: ['NAAC A+', 'MCI'],
    established: 1956,
    totalFee: 0.13,
    matchScore: 85,
    admissionChance: 42,
    verified: true,
  },
  {
    id: '3',
    name: 'IIM Ahmedabad',
    location: 'Ahmedabad',
    state: 'Gujarat',
    rank: 1,
    rankingBody: 'NIRF Management',
    stream: 'MBA',
    type: 'government',
    avgCTC: 35.0,
    highestCTC: 1.08,
    cutoff: '99.5+',
    cutoffExam: 'CAT',
    tags: ['Govt. funded', 'AACSB', 'EQUIS', 'AMBA'],
    accreditation: ['AACSB', 'EQUIS'],
    established: 1961,
    totalFee: 24.0,
    matchScore: 78,
    admissionChance: 31,
    verified: true,
  },
  {
    id: '4',
    name: 'NLS Bangalore',
    location: 'Bengaluru',
    state: 'Karnataka',
    rank: 1,
    rankingBody: 'NIRF Law',
    stream: 'Law',
    type: 'government',
    avgCTC: 22.0,
    highestCTC: 72,
    cutoff: '99+',
    cutoffExam: 'CLAT',
    tags: ['Govt. funded', 'NAAC A', 'Premier Law School'],
    accreditation: ['NAAC A', 'BCI'],
    established: 1987,
    totalFee: 3.6,
    matchScore: 88,
    admissionChance: 55,
    verified: true,
  },
  {
    id: '5',
    name: 'NID Ahmedabad',
    location: 'Ahmedabad',
    state: 'Gujarat',
    rank: 1,
    rankingBody: 'NIRF Design',
    stream: 'Design',
    type: 'government',
    avgCTC: 12.0,
    highestCTC: 45,
    cutoff: 'Top 5%',
    cutoffExam: 'NID DAT',
    tags: ['Govt. funded', 'WDO Member', 'Design Excellence'],
    accreditation: ['WDO', 'NAAC A'],
    established: 1961,
    totalFee: 5.2,
    matchScore: 74,
    admissionChance: 62,
    verified: true,
  },
  {
    id: '6',
    name: 'IIT Delhi',
    location: 'New Delhi',
    state: 'Delhi',
    rank: 2,
    rankingBody: 'NIRF',
    stream: 'Engineering',
    type: 'government',
    avgCTC: 17.2,
    highestCTC: 2.1,
    cutoff: '98.2+',
    cutoffExam: 'JEE Advanced',
    tags: ['Govt. funded', 'NAAC A++', 'NBA'],
    accreditation: ['NAAC A++', 'NBA'],
    established: 1961,
    totalFee: 2.1,
    matchScore: 89,
    admissionChance: 72,
    verified: true,
  },
]

export const exams: Exam[] = [
  {
    id: '1',
    name: 'JEE Main',
    fullName: 'Joint Entrance Examination Main',
    conductedBy: 'NTA',
    date: 'Jan 22 – Feb 1, 2025',
    registrationDeadline: 'Dec 15, 2024',
    stream: 'Engineering',
    level: 'national',
    applicants: '12L+',
  },
  {
    id: '2',
    name: 'NEET UG',
    fullName: 'National Eligibility cum Entrance Test',
    conductedBy: 'NTA',
    date: 'May 4, 2025',
    registrationDeadline: 'Mar 7, 2025',
    stream: 'Medical',
    level: 'national',
    applicants: '24L+',
  },
  {
    id: '3',
    name: 'CAT 2024',
    fullName: 'Common Admission Test',
    conductedBy: 'IIM Calcutta',
    date: 'Nov 24, 2024',
    registrationDeadline: 'Sep 13, 2024',
    stream: 'MBA',
    level: 'national',
    applicants: '3.3L+',
  },
  {
    id: '4',
    name: 'CLAT',
    fullName: 'Common Law Admission Test',
    conductedBy: 'Consortium of NLUs',
    date: 'Dec 1, 2024',
    registrationDeadline: 'Oct 15, 2024',
    stream: 'Law',
    level: 'national',
    applicants: '70K+',
  },
  {
    id: '5',
    name: 'GATE',
    fullName: 'Graduate Aptitude Test in Engineering',
    conductedBy: 'IIT Roorkee',
    date: 'Feb 1–2, 2025',
    registrationDeadline: 'Oct 3, 2024',
    stream: 'Engineering',
    level: 'national',
    applicants: '8L+',
  },
]

export const reviews: Review[] = [
  {
    id: '1',
    studentName: 'Arjun Mehta',
    initials: 'AM',
    college: 'IIT Bombay',
    course: 'B.Tech CSE',
    year: 2024,
    rating: 5,
    reviewText:
      'The research culture here is unmatched in India. World-class faculty, cutting-edge labs, and incredible peer learning. The placement cell is super active — almost every major tech company visits. The campus life is vibrant with 100+ clubs.',
    verified: true,
    pros: ['Research opportunities', 'Faculty quality', 'Placements'],
    cons: ['Intense competition', 'High workload'],
  },
  {
    id: '2',
    studentName: 'Priya Sharma',
    initials: 'PS',
    college: 'AIIMS Delhi',
    course: 'MBBS',
    year: 2023,
    rating: 5,
    reviewText:
      "Studying at AIIMS was the most rigorous and rewarding experience. Patient exposure from year one sets it apart. The hospital attachment gives you real clinical skills early. Faculty are legends in their fields. Infrastructure is world-class.",
    verified: true,
    pros: ['Clinical exposure', 'Faculty', 'Infrastructure'],
    cons: ['Extremely demanding schedule'],
  },
  {
    id: '3',
    studentName: 'Rahul Gupta',
    initials: 'RG',
    college: 'IIM Ahmedabad',
    course: 'PGP MBA',
    year: 2024,
    rating: 4,
    reviewText:
      'The case study method trains you to think under pressure. The peer network is the most valuable asset — future CEOs, founders and CXOs in your batch. The brand opens doors globally. Exhausting but completely worth it.',
    verified: true,
    pros: ['Network', 'Brand value', 'Placements'],
    cons: ['Very expensive', 'Work-life balance'],
  },
]

export const stats = [
  { value: '6000+', label: 'Institutions' },
  { value: '200+', label: 'Student reviews' },
  { value: '50+', label: 'Entrance exams' },
  { value: '10,000+', label: 'Monthly students' },
]

export const streamFilters = [
  { label: 'All', value: 'all' },
  { label: 'Engineering', value: 'engineering' },
  { label: 'Medical', value: 'medical' },
  { label: 'MBA', value: 'mba' },
  { label: 'Law', value: 'law' },
  { label: 'Design', value: 'design' },
]
